CPPFLAGS=-O3 -Ofast -Wall -Wextra -pedantic -fconcepts --std=c++17 -marc=native
LDFLAGS=-g
LDLIBS=-lpthread -lm -fopenmp

# g++ -O3 -Ofast -Wall -Wextra -pedantic -fconcepts --std=c++17 -pthread -fopenmp -o 2_block_stl 2_block_stl.cpp


