CPPFLAGS=-O3 -Wall -Wextra -pedantic -fconcepts --std=c++17 -marc=native
LDFLAGS=-g
LDLIBS=-pthread -lm -fopenmp

# g++ -O3 -Wall -Wextra -pedantic -fconcepts --std=c++17 -pthread -o 2_block_stl 2_block_stl.cpp
